const KEY = 'jornal-digital-edicoes';
const DB_NAME = 'jornal-digital-arquivos';
const STORE = 'edicoes';
const $ = (id) => document.getElementById(id);
const form = $('issueForm'), list = $('issueList'), fileInput = $('fileInput'), filePreview = $('filePreview');
const adminModal = $('adminModal'), viewModal = $('viewModal');
let selectedFiles = [];

const demo = [{ id: 'demo', title: 'Jornal de Vargem Grande', edition: '204', date: '2026-09-28', category: 'Local', summary: 'Edição especial com destaques da feira, eventos culturais e entrevistas com moradores locais.', fileName: 'capa-jornal.svg', fileType: 'image/svg+xml', fileData: 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1100"><rect width="800" height="1100" fill="#f2e7d3"/><rect x="65" y="65" width="670" height="970" fill="#fffaf3" stroke="#222" stroke-width="4"/><text x="400" y="260" text-anchor="middle" font-family="Georgia" font-size="78">JORNAL</text><text x="400" y="340" text-anchor="middle" font-family="Georgia" font-size="40" fill="#8b1e1e">VARGEM GRANDE</text><line x1="150" y1="400" x2="650" y2="400" stroke="#222" stroke-width="3"/><text x="400" y="540" text-anchor="middle" font-family="Arial" font-size="28">ED. 204 · 28 DE SETEMBRO</text><text x="400" y="700" text-anchor="middle" font-family="Arial" font-size="26">Feira local • Cultura • Esportes</text></svg>') }];

function openDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function getAll() { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE, 'readonly').objectStore(STORE).getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function put(item) { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE, 'readwrite').objectStore(STORE).put(item); request.onsuccess = resolve; request.onerror = () => reject(request.error); }); }
async function remove(id) { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE, 'readwrite').objectStore(STORE).delete(id); request.onsuccess = resolve; request.onerror = () => reject(request.error); }); }

async function loadIssues() {
  try { const stored = await getAll(); if (stored.length) return stored; const old = JSON.parse(localStorage.getItem(KEY) || '[]'); const initial = old.length ? old : demo; for (const item of initial) await put(item); return initial; }
  catch (error) { console.error(error); return demo; }
}
function niceDate(value) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(value + 'T00:00:00')); }
function filesOf(issue) { return issue.files?.length ? issue.files : (issue.fileData ? [{ name: issue.fileName, type: issue.fileType, data: issue.fileData }] : []); }
function media(file, className = '') { if (!file?.data) return '<div class="empty-state">Arquivo não disponível</div>'; if ((file.type || '').startsWith('image/')) return `<img class="${className}" src="${file.data}" alt="Imagem do jornal">`; if ((file.type || '').startsWith('video/')) return `<video class="${className}" src="${file.data}" controls playsinline></video>`; if (file.type === 'application/pdf' || file.name?.toLowerCase().endsWith('.pdf')) return `<iframe class="${className}" src="${file.data}" title="PDF do jornal"></iframe>`; return `<div class="empty-state"><strong>${file.name}</strong><br>Use o botão para abrir este documento.</div>`; }
function render(issues) { if (!issues.length) { list.innerHTML = '<div class="empty-state">Nenhuma edição publicada.</div>'; return; } list.innerHTML = issues.slice().reverse().map((i) => { const files = filesOf(i), cover = files.find(f => (f.type || '').startsWith('image/')); return `<article class="issue-card">${cover ? media(cover, 'issue-cover') : ''}<div class="issue-header"><span class="issue-tag">${i.category}</span><span class="issue-meta">Edição ${i.edition}</span></div><div><h3>${i.title}</h3><div class="issue-meta">${niceDate(i.date)} · ${files.length} arquivo(s)</div></div><p class="issue-summary">${i.summary || ''}</p><div class="issue-actions"><button class="action-btn" data-view="${i.id}">Abrir jornal</button></div></article>`; }).join(''); document.querySelectorAll('[data-view]').forEach(b => b.onclick = async () => openView((await loadIssues()).find(i => i.id === b.dataset.view))); }
function updatePreview() { if (!selectedFiles.length) { filePreview.className = 'file-preview empty'; filePreview.textContent = 'Nenhum arquivo selecionado'; return; } filePreview.className = 'file-preview'; filePreview.innerHTML = `<div>${selectedFiles.map(f => `<div>✓ ${f.name}</div>`).join('')}</div>`; }
fileInput.onchange = async (event) => { selectedFiles = await Promise.all([...event.target.files].map(file => new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type || '', data: reader.result }); reader.readAsDataURL(file); }))); updatePreview(); };
function openAdmin() { adminModal.classList.remove('hidden'); adminModal.setAttribute('aria-hidden', 'false'); }
function closeAdmin() { adminModal.classList.add('hidden'); adminModal.setAttribute('aria-hidden', 'true'); }
async function openView(issue) { if (!issue) return; const files = filesOf(issue); viewModal.classList.remove('hidden'); viewModal.setAttribute('aria-hidden', 'false'); $('modalContent').innerHTML = `<div class="modal-content"><div class="modal-preview">${media(files[0])}</div><div class="modal-details"><div class="modal-tag">${issue.category}</div><h3 id="modalTitle">${issue.title}</h3><div class="issue-meta"><b>Edição ${issue.edition}</b> · ${niceDate(issue.date)}</div><p class="modal-summary">${issue.summary || ''}</p><h4>Arquivos da edição</h4><div class="file-list">${files.map((f, index) => `<button class="action-btn file-choice" data-file="${index}">${f.name}</button>`).join('')}</div><div class="modal-actions"><button class="secondary-btn" id="deleteIssue">Excluir</button></div></div></div>`; const preview = $('modalContent').querySelector('.modal-preview'); document.querySelectorAll('.file-choice').forEach(button => button.onclick = () => { preview.innerHTML = media(files[Number(button.dataset.file)]); }); $('deleteIssue').onclick = async () => { await remove(issue.id); render(await loadIssues()); closeView(); }; }
function closeView() { viewModal.classList.add('hidden'); viewModal.setAttribute('aria-hidden', 'true'); }
form.onsubmit = async (event) => { event.preventDefault(); const item = { id: crypto.randomUUID(), title: $('title').value.trim(), edition: $('edition').value.trim(), date: $('date').value, category: $('category').value, summary: $('summary').value.trim(), files: selectedFiles }; if (!item.title || !item.edition || !item.date) { alert('Preencha título, edição e data.'); return; } try { await put(item); render(await loadIssues()); form.reset(); selectedFiles = []; updatePreview(); closeAdmin(); } catch (error) { alert('Não foi possível guardar o arquivo. Tente arquivos menores.'); console.error(error); } };
$('adminBtn').onclick = openAdmin; $('closeAdminModal').onclick = closeAdmin; $('closeViewModal').onclick = closeView; $('resetDemo').onclick = async () => { for (const issue of await loadIssues()) await remove(issue.id); for (const issue of demo) await put(issue); render(demo); form.reset(); selectedFiles = []; updatePreview(); }; document.querySelectorAll('.modal-overlay').forEach(o => o.onclick = () => o.dataset.close === 'admin' ? closeAdmin() : closeView()); document.onkeydown = e => { if (e.key === 'Escape') { closeAdmin(); closeView(); } };
loadIssues().then(render); updatePreview();
