const KEY='jornal-digital-edicoes';
const $=id=>document.getElementById(id);
const form=$('issueForm'),list=$('issueList'),fileInput=$('fileInput'),filePreview=$('filePreview');
const adminModal=$('adminModal'),viewModal=$('viewModal');
let fileData='',fileName='',fileType='';
const demo=[{id:'demo',title:'Jornal de Vargem Grande',edition:'204',date:'2026-09-28',category:'Local',summary:'Edição especial com destaques da feira, eventos culturais e entrevistas com moradores locais.',fileName:'capa-jornal.svg',fileType:'image/svg+xml',fileData:'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1100"><rect width="800" height="1100" fill="#f2e7d3"/><rect x="65" y="65" width="670" height="970" fill="#fffaf3" stroke="#222" stroke-width="4"/><text x="400" y="260" text-anchor="middle" font-family="Georgia" font-size="78">JORNAL</text><text x="400" y="340" text-anchor="middle" font-family="Georgia" font-size="40" fill="#8b1e1e">VARGEM GRANDE</text><line x1="150" y1="400" x2="650" y2="400" stroke="#222" stroke-width="3"/><text x="400" y="540" text-anchor="middle" font-family="Arial" font-size="28">ED. 204 · 28 DE SETEMBRO</text><text x="400" y="700" text-anchor="middle" font-family="Arial" font-size="26">Feira local • Cultura • Esportes</text></svg>')}];
let issues=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(x)&&x.length)return x;localStorage.setItem(KEY,JSON.stringify(demo));return [...demo]}catch{return [...demo]}}
function save(){localStorage.setItem(KEY,JSON.stringify(issues))}
function date(v){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(v+'T00:00:00'))}
function media(issue,cls=''){if(!issue.fileData)return '<div class="empty-state">Sem arquivo anexado</div>';const t=issue.fileType||'';if(t.startsWith('image/'))return `<img class="${cls}" src="${issue.fileData}" alt="${issue.title}">`;if(t.startsWith('video/'))return `<video class="${cls}" src="${issue.fileData}" controls playsinline></video>`;if(t==='application/pdf'||issue.fileName?.toLowerCase().endsWith('.pdf'))return `<iframe class="${cls}" src="${issue.fileData}" title="PDF"></iframe>`;return `<div class="empty-state"><strong>${issue.fileName}</strong><br>Este documento pode ser aberto pelo botão abaixo.</div>`}
function render(){if(!issues.length){list.innerHTML='<div class="empty-state">Nenhuma edição publicada.</div>';return}list.innerHTML=issues.slice().reverse().map(i=>`<article class="issue-card">${i.fileData&&i.fileType?.startsWith('image/')?media(i,'issue-cover'):''}<div class="issue-header"><span class="issue-tag">${i.category}</span><span class="issue-meta">Edição ${i.edition}</span></div><div><h3>${i.title}</h3><div class="issue-meta">${date(i.date)} · ${i.fileName||'Sem arquivo'}</div></div><p class="issue-summary">${i.summary||''}</p><div class="issue-actions"><button class="action-btn" data-view="${i.id}">Abrir jornal</button>${i.fileData?`<a class="issue-download" href="${i.fileData}" target="_blank" rel="noreferrer">Abrir arquivo</a>`:''}</div></article>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openView(issues.find(i=>i.id===b.dataset.view)))}
function preview(){if(!fileData){filePreview.className='file-preview empty';filePreview.textContent='Nenhum arquivo selecionado';return}filePreview.className='file-preview';filePreview.innerHTML=media({fileData,fileType,fileName},'')}
fileInput.onchange=e=>{const f=e.target.files[0];if(!f)return;fileName=f.name;fileType=f.type||'';const r=new FileReader();r.onload=()=>{fileData=r.result;preview()};r.readAsDataURL(f)};
function openAdmin(){adminModal.classList.remove('hidden');adminModal.setAttribute('aria-hidden','false')};function closeAdmin(){adminModal.classList.add('hidden');adminModal.setAttribute('aria-hidden','true')};function openView(i){if(!i)return;viewModal.classList.remove('hidden');viewModal.setAttribute('aria-hidden','false');$('modalContent').innerHTML=`<div class="modal-content"><div class="modal-preview">${media(i)}</div><div class="modal-details"><div class="modal-tag">${i.category}</div><h3 id="modalTitle">${i.title}</h3><div class="issue-meta"><b>Edição ${i.edition}</b> · ${date(i.date)}</div><p class="modal-summary">${i.summary||''}</p><div class="modal-actions">${i.fileData?`<a class="modal-action" href="${i.fileData}" target="_blank" rel="noreferrer">Abrir documento</a>`:''}<button class="secondary-btn" id="deleteIssue">Excluir</button></div></div></div>`;$('deleteIssue').onclick=()=>{issues=issues.filter(x=>x.id!==i.id);save();render();closeView()}}
function closeView(){viewModal.classList.add('hidden');viewModal.setAttribute('aria-hidden','true')}
form.onsubmit=e=>{e.preventDefault();const i={id:crypto.randomUUID(),title:$('title').value.trim(),edition:$('edition').value.trim(),date:$('date').value,category:$('category').value,summary:$('summary').value.trim(),fileName,fileType,fileData};if(!i.title||!i.edition||!i.date){alert('Preencha título, edição e data.');return}issues.push(i);save();render();form.reset();fileData='';fileName='';fileType='';preview();closeAdmin()};
$('adminBtn').onclick=openAdmin;$('closeAdminModal').onclick=closeAdmin;$('closeViewModal').onclick=closeView;$('resetDemo').onclick=()=>{issues=[...demo];save();render();form.reset();fileData='';fileName='';fileType='';preview()};document.querySelectorAll('.modal-overlay').forEach(x=>x.onclick=()=>x.dataset.close==='admin'?closeAdmin():closeView());document.onkeydown=e=>{if(e.key==='Escape'){closeAdmin();closeView()}};render();preview();
